### ISSUE TITLE
cannot read from FMU correctly

### ISSUE THREAD

**Issue by jywang2016** [lbl-srg/EnergyPlusToFMU#37] opened 2020-01-14 10:45 UTC
I creat a FMU from a modified EP example file. The modifide file can run successfully. However, if I try to read data from the exported FMU, the return value is always 0.

The code I used is as follows.

```
import pyfmi
model = pyfmi.load_fmu('origin3.fmu')

t_start = 60 * 60 * 24 * 336
t_end = 60 * 60 * 24 * 337
t_step_size = 10 * 60

model.instantiate_slave()
model.initialize(t_start, t_end, True)

model.get('tinw')[0]
```
The return value is 0.0. I am not sure if there is a problem in the IDF file.
[FH.zip](https://github.com/lbl-srg/EnergyPlusToFMU/files/4058675/FH.zip)

**Comment by tsnouidui** [comment] 2020-01-16 10:35
You don't have any `while loop` where you are advancing `time`  (through `do_step()`), so your output value can be updated. This is most likely the reason why you always see the same value.

**Comment by jywang2016** [comment] 2020-01-19 23:56
I'm sorry for the later response.

In fact, I removed the `while loop` for demonstrate the problem clearly. But it seems to make the problem confusing. The complete code is as follows.

```
import pyfmi
model = pyfmi.load_fmu('origin3.fmu')

t_start = 60 * 60 * 24 * 336
t_end = 60 * 60 * 24 * 337
t_step_size = 10 * 60

model.initialize(t_start, t_end, True)

for i in range(144):
    print('i',i,' tinw: ',model.get('tinw'),'\n')
    model.set('Tset1',20)
	model.set('Tset2',20)
	model.set('Tset3',20)
    t = t_start + i*t_step_size
    model.do_step(t,t_step_size,new_step = True)
```

**Comment by tsnouidui** [comment] 2020-01-20 16:33
Since I don't know how `tinw` is set-up in your model, it is hard to know where the problem is. Can you change the FMU to have one input which is also an output so you can set it, do a step, and get the value to see if it has changed?

**Comment by jywang2016** [comment] 2020-01-21 03:01
Thanks for your suggestions. My model `origin3.idf` is included in the atteched file `FH.zip`. It is modified by EnergyPlus example file `RadLoTempElecTermReheat.idf`.  `Tset1` is the temperature setpoint of  electric radaint heating system of the west zone. `tinw` is the indoor temperature of the west zone. In other word, `Tset1` is the input and `tinw` is the output. However, no matter how I change the `Tset1`, `tinw` remains the same.
Examples in EnergyPlusToFMU works well for me. But the abovementioned model makes me confused.
`Pyfmi` is not installed in my laptop. Once I can use my lab PC, I will try your suggestions ASAP to find possible problems. Anyway, thanks for your help.
[FH.zip](https://github.com/lbl-srg/EnergyPlusToFMU/files/4088992/FH.zip)

**Comment by tsnouidui** [comment] 2020-03-25 13:46
Any feedback on this? Should we close the issue?

**Closed** 2020-04-01 02:13 UTC
