### ISSUE TITLE
FMU with E+9-1

### ISSUE THREAD

**Issue by xavfa** [lbl-srg/EnergyPlusToFMU#36] opened 2019-11-12 10:25 UTC
Dear all,
I encounter the RUNPERIOD Format issue using the last release of EnerPlus FMU toolkit 2.1 and EnergyPlus 9.1 .idf file;

I'm used to generate FMU with older versions but stocked to this error wihtout idea to workaround...any idea for your side ?

My underneath project is to try making a FMU of an already couple Energplus Contam case for let say, having algorithme in matlab/simulink or other model coupling with the energy-mass coupled E+/contam tools.
I now that running .idf in the E+launch generates erros if one still have an FMU export object declared but while trying this (in order to read log files) with both FMU import and FMU export I get the error message  :  ** Severe  ** GetExternalInterfaceInput: Cannot have FMU-Import and FMU-Export interface simultaneously.
so aside from my FMU generation problem with the last release, is my project possible ?

**Comment by xavfa** [comment] 2020-01-20 21:10
Many thanks for your reply.Yes, you understood clearly : i wanted to have a full thermo aeraulic coupling into one FMU.Since Contam FMU is only working with e+ and e+ can easily be compiled into à FMU i wanted to try to export both into one and play with it in an other environnement (simulink) for control command purposes. 
Is it feasible ??Bests

-------- Message d'origine --------De : Thierry Nouidui <notifications@github.com> Date : 20/01/2020  17:47  (GMT+01:00) À : lbl-srg/EnergyPlusToFMU <EnergyPlusToFMU@noreply.github.com> Cc : xavfa <xav.faure@cegetel.net>, Author <author@noreply.github.com> Objet : Re: [lbl-srg/EnergyPlusToFMU] FMU with E+9-1 (#36) 
For the first problem, check this thread which seems to indicate that the problem comes from how you edit the IDF.
#30
For the second problem, as the error message states, you cannot have FMU-Import and FMU-Export interface simultaneously.
I don't understand the setup. What do you want to do exactly? Do you want to have an EnergyPlusFMU (model) which imports and links to ConTAM and then export that model as an FMU?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lbl-srg/EnergyPlusToFMU/issues/36?email_source=notifications\u0026email_token=ANX6ECELHK2TR6QWDJG4D43Q6XIRVA5CNFSM4JMBMBZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJNHT3A#issuecomment-576354796",
"url": "https://github.com/lbl-srg/EnergyPlusToFMU/issues/36?email_source=notifications\u0026email_token=ANX6ECELHK2TR6QWDJG4D43Q6XIRVA5CNFSM4JMBMBZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJNHT3A#issuecomment-576354796",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tsnouidui** [comment] 2020-01-21 10:55
I don't think that this will be possible simply given the fact that you can not set-up EnergyPlus in both modes (export and import mode). 
Maybe you can implement and export your Control as an FMU and import CONTAM and the Controls in EnergPlus. In that case, EnergyPlus will be the master. The drawback will be that you will have to recompile your control every-time you make changes to it.

**Comment by tsnouidui** [comment] 2020-03-25 13:50
This issue will be closed since it is a duplicate of #30.

**Closed by tsnouidui** 2020-03-25 13:50 UTC
